### ISSUE TITLE
search on properties does not seem to work

### ISSUE THREAD

**Issue by JoeriSmits** [topfullstack/nestjs-mongoose-crud#11]
`?query={"where":{"propertyName":/value/}}` Returns all results instead of the values with the condition like %value%.

**Comment by JoeriSmits** [comment]
`?query={"where":{"propertyName":{"$regex":"value"}}}` works for like %value% logic

**Comment by wxs77577** [comment]
Yes, you can use JSON only since it retrieves data like `JSON.parse(req.query.query)` in server side. It means you cannot use Date、Function or Regexp in url query. If you wanna use any data like these please refer to mongodb docs to use alternative ways (query operators) to use just like you mentioned `$regex`
